spring:
  datasource:
    url: jdbc:sqlite:d:\\db.sqlite
    username:
    password:
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: com.rabbit.fundservice.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
tiantian:
  "AppVersion": "6.4.6",
  "version": "6.4.6",
  "deviceid": "1",
  "plat": "Android",
  "product": "EFund"
